### ISSUE TITLE
Support for Getters, Setters, and Reflection

### ISSUE THREAD

**Issue by nipunayf** [nipunayf/ballerina-toml#30]
Since the TOML document is parsed into a `map<anydata>` structure, the developer has to create intermediate variables to access the tables nested deeply into it. As  a workaround, the `map<anydata>` structure can be encapsulated under a TOML class which manipulates the access methods. It may consists of the following functions:
1. Getter methods - To get the value of the provided key value pair.
2. Setter methods - To add a new key value pair, or change the value of an existing pair.
3. Reflection methods - to check if the provided key exists.

All the parameters are strings which follow the dotted key pattern. For instance, if you want to get a value of a nested key,
`anydata value = toml.get("table.inner.key");`, This invocation will traverse through the map structure to return the provided key

**Comment by sameerajayasoma** [comment]
I think the solution here is to define the TOML model as a record type and convert the map<json> into that application-specify type. 
```
Person p = check v.fromJsonWithType();
```
