### ISSUE TITLE
Support for a flat map structure

### ISSUE THREAD

**Issue by nipunayf** [nipunayf/ballerina-toml#31]
Since it is cumbersome to handle a nested table, the dotted key notation can be used as the keys of the map. 
```ballerina
// previous
map<anydata> toml = {"table": {"inner": {"key": "value"}}}

// new implementation
map<anydata> toml = {"table.inner.key": "value"}
```
Conversely, the user can set a flag to return the flatted structure rather than the original one.

**Comment by sameerajayasoma** [comment]
I think the default should be `map<anydata> toml = {"table": {"inner": {"key": "value"}}}`.

Otherwise, we won't be able to bind to user-defined types
